linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

linters-settings:
  misspell:
    locale: US

issues:
  max-same-issues: 0
  exclude-rules:
    - path: "_test\\.go|fake\\.go"
      linters: [unused]
    - path: "internal/sse/"
      linters: [errcheck]
